server:
  port: 8080

spring:
  application:
    name: smart-smoke-detection
  datasource:
    url: jdbc:mysql://localhost:3306/smart_smoke?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smartsmoke.entity
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mqtt:
  broker:
    url: tcp://192.168.130.101:1883
    client-id: smart-smoke-backend
    username: fasong
    password: fasong123
    completion-timeout: 3000
    reconnect:
      enabled: true
      max-delay: 10000
    topics:
      data-up: "smoke/+/data"          # 涓婃姤鏁版嵁鐨勮闃呬富棰?(+涓洪€氶厤绗?
      heartbeat-up: "smoke/+/heartbeat" # 蹇冭烦鐨勮闃呬富棰?
      cmd-down: "smoke/String.format/cmd"         # 涓嬪彂鎺у埗鎸囦护鐨勪富棰?(鐢?%s 鍗犱綅锛孞ava 閲岀敤 String.format 鏇挎崲)
logging:
  level:
    com.smartsmoke: debug

